feature/A2ZO-22: Add Fluent Validation
deba1/A2Z-Online pull request #23
Opened 2021-09-28 18:22 UTC by deba1

2021-09-30 16:02 UTC, MahdiFaheem requested changes

2021-09-30 16:02 UTC, MahdiFaheem commented on src/Application/DTOs/EntityDTOs/ProductDTO.cs
>  {
Remove unused using statements.

2021-09-30 16:02 UTC, MahdiFaheem commented on src/Application/Managers/OrderManager.cs
> +            IOrderRepository orderRepository,
Fix object cycle.

2021-09-30 16:02 UTC, MahdiFaheem commented on src/Application/Validators/EntityDTOValidator/OrderValidator.cs
> +
Remove new line.

2021-09-30 16:03 UTC, MahdiFaheem commented
FIx gender from string to enum in UserDTO

2021-09-30 17:35 UTC, kanismim reviewed
fix gender.

2021-10-01 17:13 UTC, AJakif approved these changes

2021-10-01 17:15 UTC, MahdiFaheem approved these changes

2021-10-01 17:15 UTC, merged