feature/A2ZO-25:Add React Project
deba1/A2Z-Online pull request #24
Opened 2021-10-07 18:31 UTC by AJakif

2021-10-10 03:53 UTC, deba1 requested changes
Good work

2021-10-10 03:53 UTC, deba1 commented on client-ui/src/app/app.tsx
> +function app() {
Always keep the name of Custom component pascal case.
```suggestion
function App() {
```

2021-10-10 03:53 UTC, deba1 commented on client-ui/src/assets/i.tsx
> +import React from 'react'
To keep the folder structure, you can create `.gitkeep` file in that folder. No need to make temporary file.

2021-10-10 04:09 UTC, MahdiFaheem requested changes
Remove the following files `favicon.ico`, `logo192.png` and `logo512.png`.

2021-10-10 06:35 UTC, kanismim approved these changes

2021-10-10 17:55 UTC, MahdiFaheem approved these changes

2021-10-11 16:51 UTC, deba1 approved these changes

2021-10-11 16:51 UTC, merged